import time

from selenium import webdriver
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()
driver.maximize_window()
driver.get("https://login.yahoo.com")
driver.find_element(By.ID, "login-username").send_keys("Banu212@yahoo.com")
time.sleep(5)
driver.execute_script("window.scrollTo(0, document.body.scrollHeight)")
driver.find_element(By.XPATH, "//label[@for='persistent']").click()
time.sleep(5)
driver.find_element(By.ID, "login-signin").click()
time.sleep(3)
driver.find_element(By.ID, "login-passwd").send_keys("PASSword@123")
driver.find_element(By.NAME, "verifyPassword").click()
time.sleep(5)
driver.find_element(By.LINK_TEXT, "Mail").click()
driver.find_element(By.LINK_TEXT, "Compose").click()
time.sleep(3)
driver.find_element(By.XPATH, "//input[@role='combobox' and @aria-owns='react-typehead-list-to']").send_keys("bindhu212@yahoo.com")
driver.find_element(By.CSS_SELECTOR, "input[data-test-id='compose-subject']").send_keys("Sending Mail")
time.sleep(4)
driver.find_element(By.CSS_SELECTOR, "div[data-test-id='rte']").send_keys("hi...\n How Are you?")
time.sleep(3)
driver.find_element(By.XPATH, "//span[text()='Send']").click()
time.sleep(5)
driver.find_element(By.XPATH, "//span[@role='presentation']").click()
time.sleep(2)
driver.find_element(By.ID, "profile-signout-link").click()
time.sleep(5)
driver.find_element(By.XPATH, "//div[text()='Sign In']").click()
time.sleep(2)
driver.find_element(By.ID, "login-username").send_keys("bindhu212@yahoo.com")
time.sleep(3)
driver.find_element(By.ID, "login-signin").click()
time.sleep(3)
driver.find_element(By.ID, "login-passwd").send_keys("PAssword@1234")
driver.find_element(By.NAME, "verifyPassword").click()
time.sleep(5)
driver.find_element(By.XPATH, "//div[@class='icon mail']").click()
time.sleep(2)
driver.find_element(By.XPATH, "//span[@role='presentation']").click()
time.sleep(4)
driver.find_element(By.ID, "profile-signout-link").click()
time.sleep(5)
print("Execution completed")