from selenium import webdriver
from selenium.webdriver.common.by import By
import time

driver=webdriver.Chrome()
driver.get("https://login.yahoo.com")
driver.maximize_window()
driver.find_element(By.ID, "login-username").send_keys('samgowda46@yahoo.com')
driver.find_element(By.ID, "login-signin").click()
time.sleep(2)
driver.find_element(By.ID, "login-passwd").send_keys('vad$A9900')
driver.find_element(By.ID, "login-signin").click()
time.sleep(4)
driver.find_element(By.LINK_TEXT, "Mail").click()
driver.find_element(By.LINK_TEXT, "Compose").click()
time.sleep(3)
driver.find_element(By.ID, "message-to-field").send_keys('amgowdru@yahoo.com')
driver.find_element(By.CSS_SELECTOR, "input[data-test-id='compose-subject']").send_keys('Test_mail')
driver.find_element(By.CSS_SELECTOR, "div[data-test-id='rte']").send_keys('Hi')
time.sleep(5)
driver.find_element(By.XPATH, "//span[.='Send']").click()
driver.find_element(By.XPATH, "//span[@role='presentation']").click()
time.sleep(2)
driver.find_element(By.ID, "profile-signout-link").click()
time.sleep(5)
driver.find_element(By.XPATH, "//div[text()='Sign In']").click()
time.sleep(2)
driver.find_element(By.LINK_TEXT, "Use another account").click()
time.sleep(2)
driver.find_element(By.ID, "login-username").send_keys('amgowdru@yahoo.com')
time.sleep(3)
driver.find_element(By.ID, "login-signin").click()
time.sleep(3)
driver.find_element(By.ID, "login-passwd").send_keys('FAKEpass@123')
driver.find_element(By.ID, "login-signin").click()
time.sleep(2)
driver.find_element(By.LINK_TEXT, "Mail").click()
time.sleep(5)
driver.find_element(By.XPATH, "//*[@id='ybarAccountMenuOpener']/div/img").click()
time.sleep(2)
driver.find_element(By.ID, "profile-signout-link").click()
time.sleep(5)
print("Successfully executed")